build-and-push:
  only:
    - main
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE" -f "Dockerfile-mco" .
    - docker push "$CI_REGISTRY_IMAGE"
