Gemfile:
  optional:
    ':test':
      - gem: cucumber
      - gem: minitar
      - gem: mtree
.github/CODEOWNERS:
  extra_owners:
    - vittoria-conseil
.rubocop.yml:
  extra:
    RSpec/MultipleMemoizedHelpers:
      Enabled: false
    RSpec/SubjectStub:
      Enabled: false
