Gemfile:
  optional:
    ':test':
      - gem: cucumber
      - gem: minitar
      - gem: mtree
.rubocop.yml:
  extra:
    RSpec/MultipleMemoizedHelpers:
      Enabled: false
    RSpec/SubjectStub:
      Enabled: false
